### PR TITLE
✨ initial support for Tray

### PR DESCRIPTION
**Pull request by manusa**
Relates to #44

### CODE REVIEW

**Comment by gabri94** [comment]
Is this actually doing something? I tryied to run the latest commit from master, but I see no tray icon.

**Comment by manusa** [comment]
You need to enable it on the settings>other pane.
It's disabled by default.
Regarding functionality, so far it doesn't do much. Not sure how it behaves on other platforms, in Linux (Gnome) it will focus the window and bring it to your active desktop

**Comment by gabri94** [comment]
I can't see any option (I'm on Linux with i3)
image

**Comment by manusa** [comment]
Maybe you didn't pull the branch or update your fork? 🤷

**Comment by gabri94** [comment]
I'm at commit 2feb32827bd1f3dc6c1f7446a3d4d66cd36a14d7 and I run it by calling:
`npx electronim`  from the root. I also deleted the older version appImage to be sure.

**Comment by manusa** [comment]
The fact that I see 0.0.86 in the shot means that you probably pulled the latest tag instead of main

**Comment by manusa** [comment]
> I'm at commit [2feb328](https://github.com/manusa/electronim/commit/2feb32827bd1f3dc6c1f7446a3d4d66cd36a14d7) and I run it by calling: `npx electronim` from the root. I also deleted the older version appImage to be sure.

You're running the latest release when invoking the npx command.

If you want to run the branch code:
```
npm install
npm start
```

**Comment by gabri94** [comment]
Thanks, now I can see the tray icon.  Unfortunately when I close the app, the tray also disappear. 

Is there a way to intercept the sigkill/sigterm and instead of closing the app, leaving it to the tray? 
 Slack and most other minimized app works like that.

**Comment by manusa** [comment]
That's the next task in the issue, "minimize to tray".
This PR just adds the initial Tray functionality.

**Comment by gabri94** [comment]
ok! i'll wait for it :D

**Pull request merged**
