### PR TITLE
Added a compare function to avoid sorting elements alphabetically

### PR DESCRIPTION
**Pull request by saffi-786**
Added a compare function to avoid sorting elements alphabetically, as said in issue #335

### CODE REVIEW

**Review by manusa — APPROVED** [review]

**Comment by manusa** [comment]
You'll need to fix the formatting (the return statement has some extra-indentation):
```
/home/runner/work/electronim/electronim/src/spell-check/dictionary.renderer/dictionary.worker.js
Error:   36:1  error  Expected indentation of 2 spaces but found 4  indent
```

**Comment by saffi-786** [comment]
Ok I'll update it

**Comment by saffi-786** [comment]
@manusa I have fixed the formatting. 
Can you please check.

**Review by manusa — APPROVED** [review]
LGTM, thx!

**Pull request merged**
