### PR TITLE
🧹 Refactored chrome-tabs module

### PR DESCRIPTION
**Pull request by manusa**
- Completely based on Preact
- chrome-tabs external dependency only used for styles
- Ditched draggabilly
- Probably fixed issue related with draggabilly on MacOS
- Fixed edge-case bugs when loading invalid settings

### CODE REVIEW

**Comment by manusa** [comment]
Please @visomar  could you verify nothing breaks on MacOS 🙏 

Hopefully, this will also fix the problem you reported when dragging tabs around on mac and `mouseup` event not being picked up.

Unlike [Draggabilly](https://draggabilly.desandro.com/), the current implementation is completely based on [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API).

**Comment by visomar** [comment]
Nothing seems to be broken on macOS, and the behavior of starting dragging without the mouseDown being held is gone, but now there is some strange blinking when the tab is cliked or at the beginning of being dragged. I'll include a gif to show it.

**Comment by visomar** [comment]
screencast 2020-08-02 12-36-41

It's difficult to describe it, but sometimes, the tab bar is duplicated right below the original one... sometimes it disappears before rerendering again. Either way, there is this blinking which is disturbing, and not ideal for the UX.

**Comment by manusa** [comment]
Gosh I hate 🍏. I think I can fix partially the issue. But the flickering when tabs change is really strange and the fix will probably be ugly.

**Comment by visomar** [comment]
How about this? Since the scope of this refactor is achieved, you proceed with this PR, and we'll think of a way to solve that in the future... ok?
It's going to be difficult for you to fix it specially if this isn't happening to you (or you don't have a way to reproduce it).

**Comment by manusa** [comment]
I can't be completely sure but I think [this commit](https://github.com/manusa/electronim/pull/31/commits/2a435db0a9bac42d9731c73f726e61f9cfe45939) may fix the issue, or at least improve the experience.

Could you retry 🙏 ?

I really don't feel comfortable making the current experience worse for macOS users (even if I hate their system),

**Comment by visomar** [comment]
It worked! Now both the issue with the drag and drop, and the blinking are gone. Good job!

**Pull request merged**
